In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data/search_cleaned.csv")
df.head()

,Start Date,End Date,Campaign Name,Ad Group Name,Targeting,Match Type,Customer Search Term,Impressions,Clicks,Click-Thru Rate (CTR),Cost Per Click (CPC),Spend,Total Advertising Cost of Sales (ACoS),Total Return on Advertising Spend (RoAS)
0,29-May-21,29-May-21,Rainforest - Manual,Broad Ad Group,bamboo kids plates,BROAD,bamboo kids plate set,2,1,50.00%,1.15,1.15,NaN,0.00
1,31-May-21,9-Jun-21,Rainforest - Manual,Broad Ad Group,bamboo kids plates,BROAD,bamboo kids plates and bowl sets,222,10,4.50%,1.50,15.01,30.03%,3.33
2,26-May-21,26-May-21,Rainforest - Manual,Broad Ad Group,bamboo kids plates,BROAD,bamboo plate set kids,7,1,14.29%,2.47,2.47,NaN,0.00
3,29-May-21,29-May-21,Rainforest - Manual,Broad Ad Group,bamboo kids plates,BROAD,grow forward kids bamboo plates and bowl sets,8,1,12.50%,1.98,1.98,NaN,0.00
4,11-Jun-21,11-Jun-21,Rainforest - Manual,Broad Ad Group,bamboo kids plates,BROAD,kids 10 inch dinner plate bamboo,1,1,100.00%,1.61,1.61,NaN,0.00